gantt
    title Roadmap Timeline
    dateFormat  YYYY-MM
    section Phase 1
    Feasibility Study :done, des1, 2025-04-01, 2025-04-30
    section Phase 2
    Development :active, des2, 2026-07-01, 9m
    section Phase 3
    Production Ready :des3, after des2, 6m